### ISSUE TITLE
Exporting by Labels

### ISSUE THREAD

**Issue by bartoszmajsak** [openshift-service-mesh/federation#143]
Introduce support for service selectors that allow users to export specific services based on labels across any namespace. 

The implementation should support `matchLabels` criteria, with `key:value` pairs.

#### Example structure

```yaml
serviceSelectors:
  - matchLabels:
      export: "true"
```
