### ISSUE TITLE
Export from selected namespace

### ISSUE THREAD

**Issue by bartoszmajsak** [openshift-service-mesh/federation#144]
Enable users to export all services from specific namespaces by defining label-based selection rules with `namespaceSelectors`. 

#### Example structure

```yaml
namespaceSelectors:
  - matchLabels:
      istio-injection: enabled
```
