### ISSUE TITLE
Connect more than 2 peers

### ISSUE THREAD

**Issue by jewertow** [openshift-service-mesh/federation#51]
Our API allows to configure only 1 remote peer, but we want to connect more meshes. However, we must know the identity of the configured peers to determine where an instance of an exported service come from, so we must also extend the `Remote` struct with the identity that will include trust domain, namespace, and service account. These 3 information are needed to verify SPIFFE ID.

The API should look as follows:
```
federation:
  meshPeers:
    local:
      ...
    remote:
    - identity:
        trustDomain: cluster.local
        namespace: istio-system
        serviceAccount: federation-controller-west
      addresses:
      - 192.168.0.1
    - identity:
        trustDomain: cluster.local
        namespace: istio-system
        serviceAccount: federation-controller-east
    - addresses:
      - 192.168.1.1
```
Alternatively, the identity could be a single field containing the SPIFFE ID.
```
federation:
  meshPeers:
    local:
      ...
    remote:
    - identity: cluster.local/ns/istio-system/sa/federation-controller-east
      addresses:
      - 192.168.0.1
    - identity: cluster.local/ns/istio-system/sa/federation-controller-west
      addresses:
      - 192.168.1.1
```

The second option is more compact, but an average Istio user does not have to know the SPIFFE ID format, and additionally, the first option allows us to assume default values, e.g. the configuration below could result in the following SPIFFE ID: `cluster.local/ns/istio-system/sa/federation-controller-east`.
```
federation:
  meshPeers:
    remote:
    - identity:
        serviceAccount: federation-controller-east
```

Note that the identities must be unique, so when we connect meshes using the same trust domain, then federation controllers must have unique service account or namespace.

Server can determine the identity from the XFCC header set by the ingress gateway.

**Related issues:**

- Identify source peer (see https://github.com/openshift-service-mesh/federation/issues/62)
