### ISSUE TITLE
Implement `matchExpressions` selector

### ISSUE THREAD

**Issue by jewertow** [openshift-service-mesh/federation#52]
Currently, we only support matching selectors using `matchLabels` rule. We should also support `matchExpressions`. E.g:
```
federation:
  exportedServiceSet:
    rules:
    - type: LabelSelector
      labelSelectors:
      - matchLabels:
          export-service: "true"
      - matchExpressions:
        - key: app
          operator: In
          values:
          - a
          - b
```
